name: Build

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
jobs:
  build_linux:
    name: "Ubuntu Latest gcc"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run cmake
      shell: bash
      run: |
        ls -la
