name: Build

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
jobs:
  build_linux:
    name: "Ubuntu Latest gcc"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run cmake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      shell: bash
      run: |
        # ls -la
        cd build
        make -j 5

    - name: Run tests
      shell: bash
      run: |
        # ls -la
        cd build
        make test

  build_macos_m1:
    name: "macOS M1"
    runs-on: macos-14
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run cmake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      shell: bash
      run: |
        # ls -la
        cd build
        make -j 4

    - name: Run tests
      shell: bash
      run: |
        # ls -la
        cd build
        make test

  build_macos_intel:
    name: "macOS Intel"
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run cmake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      shell: bash
      run: |
        # ls -la
        cd build
        make -j 4

    - name: Run tests
      shell: bash
      run: |
        # ls -la
        cd build
        make test

  build_win64:
    name: "Windows Latest MSVC"
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run cmake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake --build . -v --config Release

    - name: Run tests
      shell: cmd
      run: |
        cd build
        ctest -C Release -VV
